#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Tab.Resource", IsApplication=true)]

namespace Tab
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int blue = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int blue_selected = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int dark_brown = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int favorite = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int sample_0 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int sample_1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int sample_2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int sample_3 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int sample_4 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int sample_5 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int sample_6 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int sample_7 = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int add_btn = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int btn = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int fragmentContainer = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int imageView1 = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int img = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int list = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int peopleName = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int sampleTextView = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int tab_layout = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int txt = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int userProfileAva = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int userProfileExtra = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int userProfileFavorite = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int list_row = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PersonProfile = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Tab = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int add_tab = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int app_name = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int person_profile_title = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
